# Generated by Django 5.2.4 on 2025-07-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fornitore_databricks', models.IntegerField(blank=True, help_text='ID originale del fornitore da Databricks', null=True, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('cap', models.CharField(blank=True, max_length=10, null=True)),
                ('citta', models.CharField(blank=True, max_length=100, null=True)),
                ('prov', models.CharField(blank=True, max_length=2, null=True)),
                ('nazione', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('cell', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('codicefiscale', models.CharField(blank=True, max_length=16, null=True)),
                ('partitaiva', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('idata', models.DateTimeField(blank=True, null=True)),
                ('paga', models.CharField(blank=True, max_length=50, null=True)),
                ('ordinetot', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
            ],
            options={
                'verbose_name': 'Fornitore',
                'verbose_name_plural': 'Fornitori',
            },
        ),
    ]
