# Generated by Django 5.2.4 on 2025-07-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reorder_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornitore',
            name='prov',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
