# Generated by Django 5.2.4 on 2025-07-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reorder_system', '0002_alter_fornitore_prov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornitore',
            name='codicefiscale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
