# Generated by Django 5.2.4 on 2025-07-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reorder_system', '0003_alter_fornitore_codicefiscale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornitore',
            name='cap',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='cell',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='partitaiva',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
